from typing import Final

FREE_SPACE: Final = "FREE SPACE"

QUESTIONS: Final[list[str]] = [
    "bikes to work",
    "prefers tea over coffee",
    "has a pet",
    "speaks more than 2 languages",
    "has lived in another country",
    "loves spicy food",
    "plays an instrument",
    "has a plant collection",
    "has taken a spontaneous trip",
    "has tried a new recipe this month",
    "has read a book in the last month",
    "has a hidden talent",
    "has volunteered in the last year",
    "has learned a new skill recently",
    "has been to a live concert this year",
    "prefers working from a cafe",
    "has started a side project",
    "has built something with their hands",
    "knows how to code in a new language",
    "has met someone famous",
    "can name 3 constellations",
    "is left-handed",
    "has a morning routine",
    "does yoga or stretching regularly",
    "collects something unique",
    "has shared a playlist with others",
    "has a favorite local spot",
    "has attended a community event",
    "has made a handmade gift",
    "has taken a selfie with a pet",
]
